<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Validation\ValidationException;

class BootcampStackRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'bootcamp_id' => 'required',
            'stack_id' => 'required'
        ];
        
    }

    public function messages(): array
{
    return [
        'bootcamp_id.required' => 'A id Bootcamp is required',
        'stack_id.required' => 'A id stack is required',
    ];
}
    // protected function failedValidation(Validator $validator)
    // {
    //     $errors= (new ValidationException($validator))->errors();
    //     throw new HttpResponseException(
    //         jsend_fail($errors)
    //     );
    //     // parent::failedValidation($validator); // TODO: Change the autogenerated stub
    // }
}
